# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Georges Kunstler
tagline:             'Forest ecologist'
description:         'Researcher at <a href="http://www.irstea.fr/en/emgr" target="_blank">Mountain Ecosystems research unit Irstea</a> Grenoble, France.'
url:                 http://kunstler.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Georges Kunstler
  url:               http://www.irstea.fr/en/kunstler
  email:             georges.kunstler@irstea.fr
  github: kunstler
  twitter: GeorgesKunstler
  orcid: http://orcid.org/0000-0002-2544-1940
  google_scholar: https://scholar.google.com/citations?user=SlIUBF4AAAAJ&hl=en

# Custom vars
version:             1.0.0

# Gems
gems: ['jekyll-paginate']
paginate: 5
paginate_path: "page:num"
